### ISSUE TITLE
Root password & PostgreSQL (user: django) password help!

### ISSUE THREAD

**Issue by wethepeopleonline** [freelawproject/freelawmachine#43]
I have successfully fired up a freelawmachine vagrant box. I cannot seem to find any root password in the documentation and I cannot seem to find the password for the postgresql database "courtlistener"'s admin name "django" ... pg_dump returns authentication failed regardless of using the manage.py to set the django admin password.

How could I get this resolved please?

**Comment by mlissner** [comment]
There's a number of passwords to think about here. There's the login password for SSH into the machine, and there's the password for the DB itself. Which are you trying to use? I think most passwords are set to `password`.

**Comment by wethepeopleonline** [comment]
I have tried the following passwords on the following service daemons with failure across them all.
1) root w/ password, courtlistener, freelaw
2) postgresql username (admin user) w/ django's password, django's "admin set password" using the shell feature in manage.py, password, courtlistener and freelaw.

None of them work!

There is absolutely no way to dump the database out of your free law machine.

Also, since both our sleeves are rolled up on your free law machine project. I think when you provide the correct password to do such thing. You should also give the public the files that were pulled from:

https://github.com/freelawproject/free-law-machine

which are now 404 on https://github.com/freelawproject/free-law-machine (linked from the above link).

**Comment by mlissner** [comment]
OK, so I'm not sure what the passwords are then, but I think you have a big misconception about what's in a VM. Neither the old free law machine nor this one have the populated CL database. These are developer machines and the DB starts out empty. Usually one of the first things people do when they start dev work is to populate the DB with some sample data by scraping a few court websites.

We wouldn't want to ship the entire DB with these VMs because it's huge and that's not the purpose of these VMs.

**Comment by wethepeopleonline** [comment]
There is no misconception. 

I will await the passwords and it sure would be nice of you to make those image files available.

**Comment by mlissner** [comment]
Can you explain your goal a bit?

I'm pretty sure I deleted the old images a few years ago since they weren't useful for much of anything anymore, and never got used much in the first place.

**Comment by voutilad** [comment]
There are multiple passwords defined in a variety of Ansible files: https://github.com/freelawproject/freelawmachine/search?q=password&unscoped_q=password

They're all meant to be changed and the Django password is to be set after you build your box. The readme walks through those steps.

If you're trying to pull the pre-built images that appear to still be hosted in Vagrant Cloud (https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=freelawproject), those are 2 years old and way out of date. I no longer actively contribute to the project and I don't maintain those public images anymore. If that's the source of the 404 you're mentioning, that's why. You'll need to just follow the readme and build your own instances tailored to your local needs.

**Comment by mlissner** [comment]
I think the 404's are related to a VM we built and hosted way before you did this project, that @wethepeopleonline is interested in accessing. I've yet to understand exactly why though.

**Comment by wethepeopleonline** [comment]
@voutilad ,

Thank you for such a detailed and straight forward answer! I much appreciate your response. You are a good person. 

Thank you also for the password links. However, I do not believe that solves the password for "postgresql" user; or when listing the database ... outputs as follows:

                                   List of databases
     Name      |  Owner   | Encoding |  Collate   |   Ctype    |   Access privileges   
---------------+----------+----------+------------+------------+-----------------------
 courtlistener | django   | UTF8     | en_US.utf8 | en_US.utf8 | 
 postgres      | postgres | UTF8     | en_US.utf8 | en_US.utf8 | 
 template0     | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
               |          |          |            |            | postgres=CTc/postgres
 template1     | postgres | UTF8     | en_US.utf8 | en_US.utf8 | =c/postgres          +
               |          |          |            |            | postgres=CTc/postgres
(4 rows)

That's out of the box with a fresh Vagrant up. 

It shows that courtlistener database is owned by the user django. However there is no default django password anywhere that I have seen. And when changing the password using the python script; it still returns an authentication failed.

**Comment by mlissner** [comment]
> Thank you for such a detailed and straight forward answer! I much appreciate your response. You are a good person.

This feels like a dig at me. I hope it's not. I've tried to help you, but you're asking for things that don't make sense.

If you make more digs at me, I'll begin blocking you from freelawproject Github organization. Apologies if I've misunderstood your tone, but I don't think I have.

**Comment by wethepeopleonline** [comment]
@mlissner ,

I was being nice to another member of the community. Why the hostility?

**Comment by wethepeopleonline** [comment]
Issue(s) resolved! Thanks everyone! :)
